# app.py
import re
import html
from datetime import datetime
from urllib.parse import urlparse
from urllib.request import Request, urlopen
import streamlit as st

def url_to_filename(title: str, url: str) -> str:
    parsed = urlparse(url)
    base_name = title if title else parsed.netloc + parsed.path
    clean_name = re.sub(r"[^\w\-]", "_", base_name)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"{clean_name.strip('_')[:50]}_{timestamp}"

def clean_html_smart(html_content: str):
    """Native Smart Parser: Extracts title and structured paragraphs while stripping Wikipedia numbers completely."""
    title_match = re.search(r'<title.*?>(.*?)</title>', html_content, re.IGNORECASE | re.DOTALL)
    page_title = title_match.group(1).strip() if title_match else "Web Article Intelligence"
    page_title = html.unescape(page_title)
    page_title = re.sub(r'\s*-\s*Wikipedia.*', '', page_title, flags=re.IGNORECASE)
    
    html_content = re.sub(r'<script.*?>.*?</script>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
    html_content = re.sub(r'<style.*?>.*?</style>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
    html_content = re.sub(r'<nav.*?>.*?</nav>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
    html_content = re.sub(r'<footer.*?>.*?</footer>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
    
    html_content = re.sub(r'<sup\b[^>]*>.*?</sup>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
    html_content = re.sub(r'\[\d+\]', '', html_content)
    
    raw_blocks = re.split(r'</?(?:p|h1|h2|h3|li|div|article|section)>', html_content, flags=re.IGNORECASE)
    
    paragraphs = []
    for block in raw_blocks:
        clean_block = re.sub(r'<[^>]+>', ' ', block)
        clean_block = html.unescape(clean_block)
        clean_block = re.sub(r'\s+', ' ', clean_block).strip()
        
        if len(clean_block) > 25 and not clean_block.startswith(("http", "javascript", "{", "/*", "^")):
            clean_block = re.sub(r'\s*\[\s*edit\s*\]', '', clean_block, flags=re.IGNORECASE)
            paragraphs.append(clean_block)
            
    return page_title, paragraphs

def generate_ai_summary(paragraphs: list, sentences_count: int = 3) -> list:
    """Built-in Natural Language Extraction: Automatically summarizes the article using term weight ranking."""
    all_text = " ".join(paragraphs).lower()
    
    words = re.findall(r'\b\w{4,15}\b', all_text)
    if not words:
        return ["Insufficient text data to calculate structural context."]
        
    word_frequencies = {}
    for word in words:
        word_frequencies[word] = word_frequencies.get(word, 0) + 1
        
    max_frequency = max(word_frequencies.values())
    for word in word_frequencies:
        word_frequencies[word] = word_frequencies[word] / max_frequency
        
    sentences = []
    for p in paragraphs:
        split_sentences = re.split(r'(?<=[.!?])\s+', p)
        for s in split_sentences:
            if len(s.strip()) > 30:
                sentences.append(s.strip())
                
    sentence_scores = {}
    for sent in sentences:
        for word in re.findall(r'\b\w{4,15}\b', sent.lower()):
            if word in word_frequencies:
                sentence_scores[sent] = sentence_scores.get(sent, 0) + word_frequencies[word]
                
    ranked_sentences = sorted(sentence_scores, key=sentence_scores.get, reverse=True)
    summary_bullets = ranked_sentences[:sentences_count]
    
    return summary_bullets if summary_bullets else ["Could not isolate contextual analytical vectors."]

def create_native_pdf(title: str, source_url: str, paragraphs: list, font_size: int, ai_bullets: list) -> bytes:
    """PDF Matrix: Packs structural article content and AI summary blocks dynamically."""
    max_char_width = 90 if font_size < 11 else (75 if font_size < 14 else 60)
    line_spacing = font_size + 4
    lines = []
    
    if ai_bullets:
        lines.append("=========================================================================")
        lines.append(" AI AUTOGENERATED EXECUTIVE BRIEF /  AI 智慧文章摘要簡報")
        lines.append("=========================================================================")
        for bullet in ai_bullets:
            lines.append(f"  {bullet}")
        lines.append("=========================================================================")
        lines.append("")

    for p in paragraphs[:150]:
        words = p.split(' ')
        current_line = []
        for word in words:
            current_line.append(word)
            if len(' '.join(current_line)) > max_char_width:
                lines.append(' '.join(current_line))
                current_line = []
        if current_line:
            lines.append(' '.join(current_line))
        lines.append("")

    pdf_lines = [
        b"%PDF-1.4", b"1 0 obj", b"<< /Type /Catalog /Pages 2 0 R >>", b"endobj",
        b"2 0 obj", b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>", b"endobj",
        b"3 0 obj", f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>".encode('latin1'), b"endobj"
    ]
    
    stream_content = [
        b"BT", f"/F1 {font_size} Tf".encode('latin1'), f"{line_spacing} TL".encode('latin1'), b"45 800 Td",
        f"({title.encode('latin1', 'ignore').decode('latin1')}) Tj T*".encode('latin1'),
        f"(Source: {source_url.encode('latin1', 'ignore').decode('latin1')}) Tj T*".encode('latin1'),
        f"(Generated On: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}) Tj T*".encode('latin1'), b"T*",
    ]
    
    y_position = 730
    for line in lines[:120]:
        if y_position < 50:
            break
        clean_line = line.encode('latin1', 'ignore').decode('latin1').replace('(', '\\(').replace(')', '\\)')
        stream_content.append(f"({clean_line}) Tj T*".encode('latin1'))
        y_position -= line_spacing
        
    stream_content.append(b"ET")
    stream_binary = b"\n".join(stream_content)
    
    pdf_lines.extend([
        b"4 0 obj", f"<< /Length {len(stream_binary)} >>".encode('latin1'), b"stream", stream_binary, b"endstream", b"endobj",
        b"5 0 obj", b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", b"endobj",
        b"xref", b"0 6", b"0000000000 65535 f ", b"trailer", b"<< /Size 6 /Root 1 0 R >>", b"%%EOF"
    ])
    return b"\n".join(pdf_lines)

st.set_page_config(page_title="AI Intelligence Engine", page_icon="🤖", layout="wide")

st.sidebar.header("⚙️ System Control Center / 進階設定")
export_format = st.sidebar.selectbox("File Export Type / 導出格式:", ["Professional Document (.pdf)", "Raw Text Brief (.txt)"])
ui_font_size = st.sidebar.slider("Text Font Scaling / 字體大小調整:", min_value=10, max_value=15, value=11)

st.title("🤖 AI-Powered Enterprise Content Extraction Engine")
st.write("Deconstruct intricate web articles, filter layout numbers, and generate smart summaries instantly.")

user_url = st.text_input("🔗 Target Web URL / 請輸入採集網址:", placeholder="https://wikipedia.org")

if user_url:
    if not user_url.startswith(("http://", "https://")):
        user_url = "https://" + user_url

    if st.button("🚀 Process & Summarize Content", type="primary"):
        with st.spinner("⚡ AI Core Processing: Fetching layout payload and running matrix analytics..."):
            try:
                req = Request(user_url, headers={'User-Agent': 'Mozilla/5.0'})
                with urlopen(req, timeout=15) as response:
                    raw_html = response.read().decode('utf-8', errors='ignore')
                
                page_title, clean_paragraphs = clean_html_smart(raw_html)
                file_base = url_to_filename(page_title, user_url)
                
                if not clean_paragraphs:
                    clean_paragraphs = ["No valid article blocks could be programmatically mined from the URL context."]
                
                ai_summary_points = generate_ai_summary(clean_paragraphs, 3)
                
                if "PDF" in export_format:
                    filename = f"{file_base}.pdf"
                    file_bytes = create_native_pdf(page_title, user_url, clean_paragraphs, ui_font_size, ai_summary_points)
                    mime_type = "application/pdf"
                else:
                    filename = f"{file_base}.txt"
                    text_lines = [f"TITLE: {page_title}", f"SOURCE: {user_url}", f"TIMESTAMP: {datetime.now()}\n", "="*50, ""]
                    for b in ai_summary_points:
                        text_lines.append(f"- {b}")
                    text_lines.append("="*50 + "\n")
                    text_lines.extend(clean_paragraphs)
                    file_bytes = "\n".join(text_lines).encode('utf-8', errors='ignore')
                    mime_type = "text/plain"

                st.success(" AI Analysis Complete! Your download is packaged and ready.")
                st.download_button(
                    label=f" Download Processed {filename.split('.')[-1].upper()} Brief",
                    data=file_bytes,
                    file_name=filename,
                    mime=mime_type
                )
            except Exception as e:
                st.error(f" Core Processing Matrix Exception: {e}")
